### ISSUE TITLE
Type Target does not work

### ISSUE THREAD

**Issue by mariusbuescher** [0x0I/ansible-role-systemd#26]
Unfortunately, I was not able to create a systemd unit of type `target` with this role. When using your example, I stumbled on the problem, that no `Target` key is specified. The problems seems to be within the template, that requires a section named after the type, but I do not need the `Target` type.

Ansible version: 2.9.2
Python version: 3.8.1

Is this known?

**Comment by 0x0I** [comment]
Hey, thanks for opening this @mariusbuescher (btw apologies for the delay in response) and the issue was not known. I've responded to your PR request and can go ahead and apply a fix whenever works.
