### ISSUE TITLE
The loop variable 'item' is already in use

### ISSUE THREAD

**Issue by rymdbullen** [0x0I/ansible-role-systemd#31]
Using latest version of this role (v0.1.0) as found on Ansible Galaxy, I've got an issue like this:

```
TASK [0x0i.systemd : Render unit(letsencrypt-certbot.service) configuration] ************************************************************
[WARNING]: The loop variable 'item' is already in use. You should set the `loop_var` value in the `loop_control` option for the task to  
something else to avoid variable collisions and unexpected behavior.
...
...
```
I'm using Ansible 2.9:

    $ ansible --version
    ansible 2.9.6
      config file = /home/jstenval/.ansible.cfg
      configured module search path = ['/usr/share/ansible/modules']
      ansible python module location = /usr/lib/python3.8/site-packages/ansible
      executable location = /usr/bin/ansible
      python version = 3.8.2 (default, Apr  8 2020, 14:31:25) [GCC 9.3.0]

This was easily fixed as the comment says. In the file `tasks/common/config.yml`, adding this between the lines 15 and 16 and renaming `item` to `unit_item`:

    loop_control:
      loop_var: unit_item

Does this seems correct to you?

//Thanks

**Comment by 0x0I** [comment]
Hey, thanks for reporting this @rymdbullen. Seems correct to me :+1:
