### ISSUE TITLE
Multiple ExecStart=

### ISSUE THREAD

**Issue by Gabscap** [0x0I/ansible-role-systemd#34]
Systemd allows multiple ExecStart values, like
```
[Service]
Type=oneshot
ExecStart=/program/a
ExecStart=/program/b
```

Is it possible to create such files? Unfortunately YAML doesn't allow duplicate keys. Is there another way?

**Comment by 0x0I** [comment]
Hey @Gabscap, yea..hit a similar problem with specification of multiple `Environment` directives. Luckily, [Systemd](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Command%20lines) allows for multiple commands to be specified in a single `ExecStart=` directive using `;` as a delimiter. Specifically:

```
Multiple command lines may be concatenated in a single directive by separating them with semicolons (these semicolons must be passed as separate words). Lone semicolons may be escaped as "\;".
```

So, for example:

```
[Service]
Type=oneshot
ExecStart=/program/a;/program/b
```

Perhaps not as readable but achieves the effect.

**Comment by Gabscap** [comment]
Nice :+1: Didn't knew that.

**Comment by seocam** [comment]
@0x0I I needed to add multiple `ExecStartPre` and it seems like the `;` trick doesn't work in this case.

**Comment by seocam** [comment]
My bad. It actually works fine with using semi-colon `;`. I just had to add an extra space before it otherwise the directory I was creating would contain the ; on it's name.

`install .. mydir; othercommand` would create `mydir;`
`install .. mydir ; othercommand` creates `mydir` just fine.
